// automatically generated by the FlatBuffers compiler, do not modify

export { autostop_option_, autostop_option_T } from './autostop-option-.js';
export { hitboxes_, hitboxes_T } from './hitboxes-.js';
export { rage_global_settings, rage_global_settingsT } from './rage-global-settings.js';
export { rage_settings, rage_settingsT } from './rage-settings.js';
