// automatically generated by the FlatBuffers compiler, do not modify

export { flags_, flags_T } from './flags-.js';
export { visuals, visualsT } from './visuals.js';
export { weapons_, weapons_T } from './weapons-.js';
