// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOADERINTERFACE_H_
#define FLATBUFFERS_GENERATED_LOADERINTERFACE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct LoaderInterface;
struct LoaderInterfaceBuilder;

struct LoaderInterface FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoaderInterfaceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INTERFACES = 4
  };
  const ::flatbuffers::Vector<uint64_t> *interfaces() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_INTERFACES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INTERFACES) &&
           verifier.VerifyVector(interfaces()) &&
           verifier.EndTable();
  }
};

struct LoaderInterfaceBuilder {
  typedef LoaderInterface Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_interfaces(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> interfaces) {
    fbb_.AddOffset(LoaderInterface::VT_INTERFACES, interfaces);
  }
  explicit LoaderInterfaceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoaderInterface> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoaderInterface>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoaderInterface> CreateLoaderInterface(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> interfaces = 0) {
  LoaderInterfaceBuilder builder_(_fbb);
  builder_.add_interfaces(interfaces);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LoaderInterface> CreateLoaderInterfaceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *interfaces = nullptr) {
  auto interfaces__ = interfaces ? _fbb.CreateVector<uint64_t>(*interfaces) : 0;
  return CreateLoaderInterface(
      _fbb,
      interfaces__);
}

#endif  // FLATBUFFERS_GENERATED_LOADERINTERFACE_H_
