// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOADERMODULE_H_
#define FLATBUFFERS_GENERATED_LOADERMODULE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct LoaderModule;
struct LoaderModuleBuilder;

struct LoaderModule FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoaderModuleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODULES = 4
  };
  const ::flatbuffers::Vector<uint64_t> *modules() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_MODULES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MODULES) &&
           verifier.VerifyVector(modules()) &&
           verifier.EndTable();
  }
};

struct LoaderModuleBuilder {
  typedef LoaderModule Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_modules(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> modules) {
    fbb_.AddOffset(LoaderModule::VT_MODULES, modules);
  }
  explicit LoaderModuleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoaderModule> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoaderModule>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoaderModule> CreateLoaderModule(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> modules = 0) {
  LoaderModuleBuilder builder_(_fbb);
  builder_.add_modules(modules);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LoaderModule> CreateLoaderModuleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *modules = nullptr) {
  auto modules__ = modules ? _fbb.CreateVector<uint64_t>(*modules) : 0;
  return CreateLoaderModule(
      _fbb,
      modules__);
}

#endif  // FLATBUFFERS_GENERATED_LOADERMODULE_H_
